/* Maps content records to image slots in the generated manifest.
 * Kept separate from universities.ts / countries.ts so the fee data
 * stays purely factual, and separate from images.ts because that file
 * is regenerated by `npm run images`.
 *
 * IMAGE COVERAGE. The client's photo manifest covers six universities
 * — the ones carried over from the 2026-27 portfolio. The seventeen
 * universities added from the current brochure have no photography of
 * their own, so they resolve to country-level imagery and are
 * captioned by COUNTRY, never by a city or campus we have no picture
 * of. Getting this wrong would put a stock photo of one place under
 * the name of another on a page where families commit lakhs.
 */

/** Universities the client's photo manifest actually covers. */
export const MANIFEST_SLUGS = new Set([
  "geomedi-university-georgia",
  "kemerovo-state-medical-university",
  "north-caucasian-state-medical-academy",
  "ingush-state-university",
  "fergana-medical-institute-of-public-health",
  "university-of-south-asia-kyrgyzstan",
]);

export function hasManifest(slug: string): boolean {
  return MANIFEST_SLUGS.has(slug);
}

/** University slug → image slot. Except for GEOMEDI, the photograph
 *  shows the host country or region, not the campus building. */
export const UNI_IMAGE: Record<string, string> = {
  // Genuine photograph of the GEOMEDI building, from the client's own
  // reference site (same proprietor, reuse authorised).
  "geomedi-university-georgia": "campus-geomedi",

  // Georgia — Tbilisi and Caucasus photography.
  "avicenna-batumi-medical-university": "country-georgia-alt",
  "georgian-american-university": "u-geomedi-2",
  "georgian-national-university-seu": "u-geomedi-3",
  "east-west-university-georgia": "u-geomedi-1",
  "david-tvildiani-medical-university": "country-georgia",

  // Russia.
  "kazan-federal-university": "country-russia",
  "bashkir-state-medical-university": "country-russia-alt",
  "ulyanovsk-state-university": "u-kemerovo-3",
  "chuvash-state-medical-university": "u-ncsma-2",
  "kemerovo-state-medical-university": "uni-kemerovo",
  "north-caucasian-state-medical-academy": "uni-north-caucasian",
  "kabardino-balkarian-state-university": "u-ncsma-3",
  "ingush-state-university": "uni-ingush",

  // Kazakhstan.
  "kazakh-national-medical-university": "country-kazakhstan",
  "kazakh-russian-medical-university": "country-kazakhstan-alt",

  // China.
  "nanjing-medical-university": "country-china",
  "southern-medical-university": "country-china-alt",
  "chongqing-medical-university": "country-china",
  "tianjin-medical-university": "country-china-alt",
  "capital-medical-university": "country-china",

  // Retained.
  "fergana-medical-institute-of-public-health": "uni-fergana",
  "university-of-south-asia-kyrgyzstan": "uni-south-asia",
};

/** Caption rendered over each university photograph. Must describe
 *  what the photograph actually shows — where we have no picture of
 *  the city, the caption names the country only. */
export const UNI_IMAGE_CAPTION: Record<string, string> = {
  "geomedi-university-georgia": "GEOMEDI University, Tbilisi",

  "avicenna-batumi-medical-university": "Georgia — the Caucasus",
  "georgian-american-university": "Tbilisi, Georgia",
  "georgian-national-university-seu": "Tbilisi, Georgia",
  "east-west-university-georgia": "Old town Tbilisi, Georgia",
  "david-tvildiani-medical-university": "Tbilisi, Georgia",

  "kazan-federal-university": "Russia",
  "bashkir-state-medical-university": "Russia in winter",
  "ulyanovsk-state-university": "A Russian city",
  "chuvash-state-medical-university": "A Russian town street",
  "kemerovo-state-medical-university": "Kemerovo region, Russia",
  "north-caucasian-state-medical-academy": "North Caucasus, Russia",
  "kabardino-balkarian-state-university": "The Caucasus, southern Russia",
  "ingush-state-university": "Magas, Ingushetia, Russia",

  "kazakh-national-medical-university": "Kazakhstan",
  "kazakh-russian-medical-university": "The Kazakh steppe",

  "nanjing-medical-university": "China",
  "southern-medical-university": "China — traditional architecture",
  "chongqing-medical-university": "China",
  "tianjin-medical-university": "China — traditional architecture",
  "capital-medical-university": "China",

  "fergana-medical-institute-of-public-health": "Fergana Valley, Uzbekistan",
  "university-of-south-asia-kyrgyzstan": "Bishkek, Kyrgyzstan",
};

export function uniImage(slug: string): string {
  return UNI_IMAGE[slug] ?? "students-campus";
}

export function uniCaption(slug: string): string {
  return UNI_IMAGE_CAPTION[slug] ?? "";
}

/** Wide photograph for the page hero. Universities in the manifest use
 *  their own city skyline; the rest fall back to the country image. */
export function uniHero(slug: string): string {
  if (slug === "geomedi-university-georgia") return "uni-geomedi";
  if (hasManifest(slug)) return `uni:${slug}:City/01_Skyline`;
  return uniImage(slug);
}

const UNI_HERO_CAPTION: Record<string, string> = {
  "geomedi-university-georgia": "Tbilisi, Georgia",
};

export function uniHeroCaption(slug: string): string {
  return UNI_HERO_CAPTION[slug] ?? UNI_IMAGE_CAPTION[slug] ?? "";
}

/* ------------------------------------------------------------------
   Inline photography on a university page.

   Manifest universities use their own city and teaching shots. The
   rest use generic medical-education imagery, which the captions
   already describe generically ("Clinical rotations from year three",
   "Laboratories and practical work") rather than claiming to show
   that campus.
   ------------------------------------------------------------------ */
type UniSlot = "city" | "hospital" | "laboratory" | "students";

const SLOT_MANIFEST_KEY: Record<UniSlot, string> = {
  city: "City/03_City_Centre",
  hospital: "University/04_Hospital_Clinical",
  laboratory: "University/02_Laboratory",
  students: "University/05_Students_Indian_Students",
};

const SLOT_FALLBACK: Record<UniSlot, string> = {
  city: "students-campus",
  hospital: "hospital-ward",
  laboratory: "laboratory",
  students: "students-friends",
};

export function uniSlotImage(slug: string, slot: UniSlot): string {
  return hasManifest(slug) ? `uni:${slug}:${SLOT_MANIFEST_KEY[slot]}` : SLOT_FALLBACK[slot];
}

/** Caption for the inline city image. Only names a city where we
 *  actually hold a photograph of it. */
export function uniCityCaption(slug: string): string {
  return hasManifest(slug) ? uniCaption(slug) : "";
}

export function countryImage(slug: string): string {
  return `country-${slug}`;
}

export function countryImageAlt(slug: string): string {
  return `country-${slug}-alt`;
}

/* ------------------------------------------------------------------
   Per-university galleries. Manifest universities show their own host
   city; the rest show their country plus generic teaching imagery.
   Captions name the place, never the campus.
   ------------------------------------------------------------------ */
export interface GalleryTile {
  id: string;
  caption: string;
  span?: string;
}

const GEORGIA_TILES: GalleryTile[] = [
  { id: "u-geomedi-1", caption: "Old town Tbilisi, Georgia", span: "col-span-2 row-span-2" },
  { id: "u-geomedi-2", caption: "Tbilisi after dark" },
  { id: "country-georgia-alt", caption: "The Caucasus" },
  { id: "lecture-hall", caption: "Lectures entirely in English", span: "sm:col-span-2" },
];

const RUSSIA_TILES: GalleryTile[] = [
  { id: "country-russia", caption: "Russian city architecture", span: "col-span-2 row-span-2" },
  { id: "country-russia-alt", caption: "Russia in winter" },
  { id: "hospital-ward", caption: "Large teaching hospitals" },
  { id: "anatomy", caption: "Anatomy and dissection halls", span: "sm:col-span-2" },
];

const KAZAKHSTAN_TILES: GalleryTile[] = [
  { id: "country-kazakhstan", caption: "Modern Kazakh architecture", span: "col-span-2 row-span-2" },
  { id: "country-kazakhstan-alt", caption: "The Kazakh steppe" },
  { id: "lecture-hall", caption: "Teaching in English" },
  { id: "students-campus", caption: "Campus life", span: "sm:col-span-2" },
];

const CHINA_TILES: GalleryTile[] = [
  { id: "country-china", caption: "Chinese city skylines", span: "col-span-2 row-span-2" },
  { id: "country-china-alt", caption: "Traditional architecture" },
  { id: "hospital-ward", caption: "Large affiliated teaching hospitals" },
  { id: "laboratory", caption: "Advanced simulation laboratories", span: "sm:col-span-2" },
];

export const UNI_GALLERY: Record<string, GalleryTile[]> = {
  "geomedi-university-georgia": [
    { id: "u-geomedi-1", caption: "Old town Tbilisi, Georgia", span: "col-span-2 row-span-2" },
    { id: "u-geomedi-2", caption: "Tbilisi after dark" },
    { id: "u-geomedi-3", caption: "Street life in the capital" },
    { id: "u-geomedi-4", caption: "Teaching laboratories", span: "sm:col-span-2" },
  ],
  "avicenna-batumi-medical-university": GEORGIA_TILES,
  "georgian-american-university": GEORGIA_TILES,
  "georgian-national-university-seu": GEORGIA_TILES,
  "east-west-university-georgia": GEORGIA_TILES,
  "david-tvildiani-medical-university": GEORGIA_TILES,

  "kazan-federal-university": RUSSIA_TILES,
  "bashkir-state-medical-university": RUSSIA_TILES,
  "ulyanovsk-state-university": RUSSIA_TILES,
  "chuvash-state-medical-university": RUSSIA_TILES,
  "kemerovo-state-medical-university": [
    { id: "u-kemerovo-1", caption: "Kemerovo region, Siberia", span: "col-span-2 row-span-2" },
    { id: "u-kemerovo-2", caption: "Siberian winter" },
    { id: "u-kemerovo-3", caption: "City housing near campus" },
    { id: "u-kemerovo-4", caption: "Hospital rotations", span: "sm:col-span-2" },
  ],
  "north-caucasian-state-medical-academy": [
    { id: "u-ncsma-1", caption: "The North Caucasus", span: "col-span-2 row-span-2" },
    { id: "u-ncsma-2", caption: "Cherkessk and around" },
    { id: "u-ncsma-3", caption: "River valleys of the region" },
    { id: "u-ncsma-4", caption: "Anatomy teaching", span: "sm:col-span-2" },
  ],
  "kabardino-balkarian-state-university": RUSSIA_TILES,
  "ingush-state-university": [
    { id: "u-ingush-1", caption: "Magas — a purpose-built capital", span: "col-span-2 row-span-2" },
    { id: "u-ingush-2", caption: "Ingushetia's mountains" },
    { id: "u-ingush-3", caption: "New city districts" },
    { id: "u-ingush-4", caption: "Simulation training", span: "sm:col-span-2" },
  ],

  "kazakh-national-medical-university": KAZAKHSTAN_TILES,
  "kazakh-russian-medical-university": KAZAKHSTAN_TILES,

  "nanjing-medical-university": CHINA_TILES,
  "southern-medical-university": CHINA_TILES,
  "chongqing-medical-university": CHINA_TILES,
  "tianjin-medical-university": CHINA_TILES,
  "capital-medical-university": CHINA_TILES,

  "fergana-medical-institute-of-public-health": [
    { id: "u-fergana-1", caption: "Fergana Valley, Uzbekistan", span: "col-span-2 row-span-2" },
    { id: "u-fergana-2", caption: "Local bazaars" },
    { id: "u-fergana-3", caption: "Modern Uzbekistan" },
    { id: "u-fergana-4", caption: "Laboratory work", span: "sm:col-span-2" },
  ],
  "university-of-south-asia-kyrgyzstan": [
    { id: "u-southasia-1", caption: "Bishkek, Kyrgyzstan", span: "col-span-2 row-span-2" },
    { id: "u-southasia-2", caption: "The mountains behind the city" },
    { id: "u-southasia-3", caption: "Kyrgyz landscapes" },
    { id: "u-southasia-4", caption: "Lectures in English", span: "sm:col-span-2" },
  ],
};

export function uniGallery(slug: string): GalleryTile[] {
  return UNI_GALLERY[slug] ?? [];
}

/** Country galleries, assembled from the per-university sets so each
 *  destination page shows its own places rather than a shared set. */
export const COUNTRY_GALLERY: Record<string, GalleryTile[]> = {
  georgia: [
    { id: "u-geomedi-1", caption: "Old town Tbilisi", span: "col-span-2 row-span-2" },
    { id: "u-geomedi-2", caption: "Tbilisi after dark" },
    { id: "country-georgia-alt", caption: "The Caucasus" },
    { id: "u-geomedi-3", caption: "Street life in the capital", span: "sm:col-span-2" },
  ],
  russia: [
    { id: "u-kemerovo-1", caption: "Kemerovo region, Siberia", span: "col-span-2 row-span-2" },
    { id: "u-ncsma-1", caption: "The North Caucasus" },
    { id: "u-ingush-1", caption: "Magas, Ingushetia" },
    { id: "u-kemerovo-2", caption: "Russian winter", span: "sm:col-span-2" },
  ],
  kazakhstan: KAZAKHSTAN_TILES,
  china: CHINA_TILES,
  uzbekistan: [
    { id: "u-fergana-1", caption: "Fergana Valley", span: "col-span-2 row-span-2" },
    { id: "country-uzbekistan", caption: "Historic tilework" },
    { id: "u-fergana-2", caption: "Local bazaars" },
    { id: "u-fergana-3", caption: "Modern Uzbekistan", span: "sm:col-span-2" },
  ],
  kyrgyzstan: [
    { id: "u-southasia-1", caption: "Bishkek", span: "col-span-2 row-span-2" },
    { id: "u-southasia-2", caption: "Mountains behind the city" },
    { id: "country-kyrgyzstan", caption: "Kyrgyz highlands" },
    { id: "u-southasia-3", caption: "Lakes and valleys", span: "sm:col-span-2" },
  ],
};

export function countryGallery(slug: string): GalleryTile[] {
  return COUNTRY_GALLERY[slug] ?? [];
}

/* ------------------------------------------------------------------
   Destination pages prefer the client manifest's City/* photographs,
   which are genuine shots of the cities we actually place students
   into. Countries with no manifest coverage (China, Kazakhstan) fall
   back to the country gallery above.
   ------------------------------------------------------------------ */
const COUNTRY_CITY_SOURCES: Record<string, { slug: string; label: string }[]> = {
  georgia: [{ slug: "geomedi-university-georgia", label: "Tbilisi" }],
  russia: [
    { slug: "kemerovo-state-medical-university", label: "Kemerovo" },
    { slug: "north-caucasian-state-medical-academy", label: "Cherkessk" },
    { slug: "ingush-state-university", label: "Magas" },
  ],
  uzbekistan: [{ slug: "fergana-medical-institute-of-public-health", label: "Fergana" }],
  kyrgyzstan: [{ slug: "university-of-south-asia-kyrgyzstan", label: "Bishkek" }],
};

const CITY_SLOT_LABEL: Record<string, string> = {
  "City/01_Skyline": "Skyline",
  "City/02_Landmark": "Landmark",
  "City/03_City_Centre": "City centre",
  "City/04_City_Life": "Everyday life",
};

/** Returns `uni:` image ids plus captions for a country's cities.
 *  One country with three universities (Russia) shows one slot from
 *  each city first, so the gallery reads as a tour of the country
 *  rather than four angles on one town. */
export function countryCityTiles(countrySlug: string): GalleryTile[] {
  const sources = COUNTRY_CITY_SOURCES[countrySlug];
  if (!sources) return [];

  const slots = Object.keys(CITY_SLOT_LABEL);
  const tiles: GalleryTile[] = [];

  if (sources.length === 1) {
    const { slug, label } = sources[0];
    slots.forEach((key) => {
      tiles.push({
        id: `uni:${slug}:${key}`,
        caption: `${label} — ${CITY_SLOT_LABEL[key]}`,
      });
    });
  } else {
    // Round-robin across cities, one slot each, then wrap.
    for (let i = 0; i < slots.length; i++) {
      const src = sources[i % sources.length];
      tiles.push({
        id: `uni:${src.slug}:${slots[i]}`,
        caption: `${src.label} — ${CITY_SLOT_LABEL[slots[i]]}`,
      });
    }
  }

  // Bento emphasis on the first and last tiles.
  if (tiles[0]) tiles[0].span = "col-span-2 row-span-2";
  if (tiles[3]) tiles[3].span = "col-span-2";
  return tiles;
}

/** Photographs used in the generic "life abroad" gallery. */
export const LIFE_GALLERY = [
  { id: "clinical-training", caption: "Clinical training from year three", span: "col-span-2 row-span-2" },
  { id: "laboratory", caption: "Modern teaching laboratories" },
  { id: "library", caption: "University libraries" },
  { id: "indian-food", caption: "Indian mess on or near every campus" },
  { id: "hostel-room", caption: "Hostel accommodation" },
  { id: "students-friends", caption: "An Indian community already there", span: "sm:col-span-2" },
  { id: "lecture-hall", caption: "Lectures entirely in English" },
  { id: "anatomy", caption: "Anatomy and dissection halls" },
  { id: "graduation", caption: "Graduation — five to six years on", span: "sm:col-span-2" },
  { id: "surgery", caption: "Operating theatre exposure" },
  { id: "students-study", caption: "FMGE preparation alongside coursework" },
] as const;

/** Service slug → image slot. */
export const SERVICE_IMAGE: Record<string, string> = {
  "career-counselling": "counselling",
  "university-selection": "student-laptop",
  "application-guidance": "documents",
  "admission-support": "consultation",
  "documentation-support": "visa-stamp",
  "visa-assistance": "visa-stamp",
  "travel-assistance": "aeroplane",
  "pre-departure-briefing": "airport",
  "post-arrival-support": "hostel-room",
  "fmge-next-guidance": "students-study",
};

/** Process step → image slot. */
export const PROCESS_IMAGE: Record<number, string> = {
  1: "counselling",
  2: "student-laptop",
  3: "documents",
  4: "visa-stamp",
  5: "airport",
};

/** The rolling strips on the homepage. */
export const MARQUEE_TOP = [
  "country-georgia",
  "clinical-training",
  "country-china",
  "students-campus",
  "country-kazakhstan",
  "laboratory",
  "country-uzbekistan",
  "graduation",
];

export const MARQUEE_BOTTOM = [
  "library",
  "country-russia",
  "students-friends",
  "country-china-alt",
  "lecture-hall",
  "country-kyrgyzstan",
  "indian-food",
  "country-georgia-alt",
];

export const MARQUEE_CAPTIONS: Record<string, string> = {
  "country-georgia": "Tbilisi, Georgia",
  "country-georgia-alt": "Caucasus, Georgia",
  "country-uzbekistan": "Uzbekistan",
  "country-kyrgyzstan": "Kyrgyzstan",
  "country-russia": "Russia",
  "country-kazakhstan": "Kazakhstan",
  "country-china": "China",
  "country-china-alt": "China",
  "clinical-training": "Clinical training",
  "students-campus": "Campus life",
  "laboratory": "Teaching laboratories",
  "graduation": "Graduation day",
  "library": "University library",
  "students-friends": "Indian student community",
  "lecture-hall": "Lectures in English",
  "indian-food": "Indian mess",
};
