/* Maps content records to image slots in the generated manifest.
 * Kept separate from universities.ts / countries.ts so the fee data
 * stays purely factual, and separate from images.ts because that file
 * is regenerated by `npm run images`. */

/** University slug → image slot. The photograph shows the host CITY or
 *  region, not the campus building — we do not have licensed photography
 *  of these specific institutions, and captioning a stock building as a
 *  named university on a page where families commit lakhs would be a
 *  misrepresentation. Captions name the place, truthfully. */
export const UNI_IMAGE: Record<string, string> = {
  // Genuine photograph of the GEOMEDI building, from the client's own
  // reference site (same proprietor, reuse authorised). Captioned as
  // the university because it actually is the university.
  "geomedi-university-georgia": "campus-geomedi",
  "kemerovo-state-medical-university": "uni-kemerovo",
  "north-caucasian-state-medical-academy": "uni-north-caucasian",
  "ingush-state-university": "uni-ingush",
  "fergana-medical-institute-of-public-health": "uni-fergana",
  "university-of-south-asia-kyrgyzstan": "uni-south-asia",
  "nepal-mbbs-universities": "uni-nepal",
};

/** Caption rendered over each university photograph. */
export const UNI_IMAGE_CAPTION: Record<string, string> = {
  "geomedi-university-georgia": "GEOMEDI University, Tbilisi",
  "kemerovo-state-medical-university": "Kemerovo region, Russia",
  "north-caucasian-state-medical-academy": "North Caucasus, Russia",
  "ingush-state-university": "Magas, Ingushetia, Russia",
  "fergana-medical-institute-of-public-health": "Fergana Valley, Uzbekistan",
  "university-of-south-asia-kyrgyzstan": "Bishkek, Kyrgyzstan",
  "nepal-mbbs-universities": "Kathmandu Valley, Nepal",
};

export function uniImage(slug: string): string {
  return UNI_IMAGE[slug] ?? "students-campus";
}

/** Wide, high-resolution photograph for the page hero. Where we hold a
 *  genuine campus shot it is usually a narrow banner crop, so the hero
 *  falls back to the host city at full resolution. */
export const UNI_HERO: Record<string, string> = {
  "geomedi-university-georgia": "uni-geomedi",
};

export function uniHero(slug: string): string {
  return UNI_HERO[slug] ?? uniImage(slug);
}

/** Caption for the hero, which shows the city rather than the campus. */
export const UNI_HERO_CAPTION: Record<string, string> = {
  "geomedi-university-georgia": "Tbilisi, Georgia",
};

export function uniHeroCaption(slug: string): string {
  return UNI_HERO_CAPTION[slug] ?? UNI_IMAGE_CAPTION[slug] ?? "";
}

export function uniCaption(slug: string): string {
  return UNI_IMAGE_CAPTION[slug] ?? "";
}

export function countryImage(slug: string): string {
  return `country-${slug}`;
}

export function countryImageAlt(slug: string): string {
  return `country-${slug}-alt`;
}

/* ------------------------------------------------------------------
   Per-university galleries. Each university page shows its own four
   photographs so no two pages look alike. The first three are the
   real host city or region; the fourth is a medical scene, varied
   per university. Captions name the place, never the campus.
   ------------------------------------------------------------------ */
export interface GalleryTile {
  id: string;
  caption: string;
  span?: string;
}

export const UNI_GALLERY: Record<string, GalleryTile[]> = {
  "geomedi-university-georgia": [
    { id: "u-geomedi-1", caption: "Old town Tbilisi, Georgia", span: "col-span-2 row-span-2" },
    { id: "u-geomedi-2", caption: "Tbilisi after dark" },
    { id: "u-geomedi-3", caption: "Street life in the capital" },
    { id: "u-geomedi-4", caption: "Teaching laboratories", span: "col-span-2" },
  ],
  "kemerovo-state-medical-university": [
    { id: "u-kemerovo-1", caption: "Kemerovo region, Siberia", span: "col-span-2 row-span-2" },
    { id: "u-kemerovo-2", caption: "Siberian winter" },
    { id: "u-kemerovo-3", caption: "City housing near campus" },
    { id: "u-kemerovo-4", caption: "Hospital rotations", span: "col-span-2" },
  ],
  "north-caucasian-state-medical-academy": [
    { id: "u-ncsma-1", caption: "The North Caucasus", span: "col-span-2 row-span-2" },
    { id: "u-ncsma-2", caption: "Cherkessk and around" },
    { id: "u-ncsma-3", caption: "River valleys of the region" },
    { id: "u-ncsma-4", caption: "Anatomy teaching", span: "col-span-2" },
  ],
  "ingush-state-university": [
    { id: "u-ingush-1", caption: "Magas — a purpose-built capital", span: "col-span-2 row-span-2" },
    { id: "u-ingush-2", caption: "Ingushetia's mountains" },
    { id: "u-ingush-3", caption: "New city districts" },
    { id: "u-ingush-4", caption: "Simulation training", span: "col-span-2" },
  ],
  "fergana-medical-institute-of-public-health": [
    { id: "u-fergana-1", caption: "Fergana Valley, Uzbekistan", span: "col-span-2 row-span-2" },
    { id: "u-fergana-2", caption: "Local bazaars" },
    { id: "u-fergana-3", caption: "Modern Uzbekistan" },
    { id: "u-fergana-4", caption: "Laboratory work", span: "col-span-2" },
  ],
  "university-of-south-asia-kyrgyzstan": [
    { id: "u-southasia-1", caption: "Bishkek, Kyrgyzstan", span: "col-span-2 row-span-2" },
    { id: "u-southasia-2", caption: "The mountains behind the city" },
    { id: "u-southasia-3", caption: "Kyrgyz landscapes" },
    { id: "u-southasia-4", caption: "Lectures in English", span: "col-span-2" },
  ],
  "nepal-mbbs-universities": [
    { id: "u-nepal-1", caption: "Kathmandu street markets", span: "col-span-2 row-span-2" },
    { id: "u-nepal-2", caption: "Nepali cities in the hills" },
    { id: "u-nepal-3", caption: "Temple architecture" },
    { id: "u-nepal-4", caption: "Clinical consultation", span: "col-span-2" },
  ],
};

export function uniGallery(slug: string): GalleryTile[] {
  return UNI_GALLERY[slug] ?? [];
}

/** Country galleries, assembled from the per-university sets so each
 *  destination page shows its own places rather than a shared set. */
export const COUNTRY_GALLERY: Record<string, GalleryTile[]> = {
  georgia: [
    { id: "u-geomedi-1", caption: "Old town Tbilisi", span: "col-span-2 row-span-2" },
    { id: "u-geomedi-2", caption: "Tbilisi after dark" },
    { id: "country-georgia-alt", caption: "The Caucasus" },
    { id: "u-geomedi-3", caption: "Street life in the capital", span: "col-span-2" },
  ],
  russia: [
    { id: "u-kemerovo-1", caption: "Kemerovo region, Siberia", span: "col-span-2 row-span-2" },
    { id: "u-ncsma-1", caption: "The North Caucasus" },
    { id: "u-ingush-1", caption: "Magas, Ingushetia" },
    { id: "u-kemerovo-2", caption: "Russian winter", span: "col-span-2" },
  ],
  uzbekistan: [
    { id: "u-fergana-1", caption: "Fergana Valley", span: "col-span-2 row-span-2" },
    { id: "country-uzbekistan", caption: "Historic tilework" },
    { id: "u-fergana-2", caption: "Local bazaars" },
    { id: "u-fergana-3", caption: "Modern Uzbekistan", span: "col-span-2" },
  ],
  kyrgyzstan: [
    { id: "u-southasia-1", caption: "Bishkek", span: "col-span-2 row-span-2" },
    { id: "u-southasia-2", caption: "Mountains behind the city" },
    { id: "country-kyrgyzstan", caption: "Kyrgyz highlands" },
    { id: "u-southasia-3", caption: "Lakes and valleys", span: "col-span-2" },
  ],
  nepal: [
    { id: "u-nepal-1", caption: "Kathmandu street markets", span: "col-span-2 row-span-2" },
    { id: "country-nepal-alt", caption: "The Himalayas" },
    { id: "u-nepal-3", caption: "Temple architecture" },
    { id: "u-nepal-2", caption: "Cities in the hills", span: "col-span-2" },
  ],
  china: [
    { id: "country-china", caption: "Chinese city skylines", span: "col-span-2 row-span-2" },
    { id: "country-china-alt", caption: "Traditional architecture" },
    { id: "hospital-ward", caption: "Large teaching hospitals" },
    { id: "laboratory", caption: "Well-funded research", span: "col-span-2" },
  ],
  kazakhstan: [
    { id: "country-kazakhstan", caption: "Modern Kazakh architecture", span: "col-span-2 row-span-2" },
    { id: "country-kazakhstan-alt", caption: "The Kazakh steppe" },
    { id: "lecture-hall", caption: "Teaching in English" },
    { id: "students-campus", caption: "Campus life", span: "col-span-2" },
  ],
};

export function countryGallery(slug: string): GalleryTile[] {
  return COUNTRY_GALLERY[slug] ?? [];
}

/* ------------------------------------------------------------------
   Destination pages prefer the client manifest's City/* photographs,
   which are genuine shots of the cities we actually place students
   into. Countries with no university in the portfolio (China,
   Kazakhstan) keep the generic country set above.
   ------------------------------------------------------------------ */
const COUNTRY_CITY_SOURCES: Record<string, { slug: string; label: string }[]> = {
  georgia: [{ slug: "geomedi-university-georgia", label: "Tbilisi" }],
  russia: [
    { slug: "kemerovo-state-medical-university", label: "Kemerovo" },
    { slug: "north-caucasian-state-medical-academy", label: "Cherkessk" },
    { slug: "ingush-state-university", label: "Magas" },
  ],
  uzbekistan: [{ slug: "fergana-medical-institute-of-public-health", label: "Fergana" }],
  kyrgyzstan: [{ slug: "university-of-south-asia-kyrgyzstan", label: "Bishkek" }],
  nepal: [{ slug: "nepal-mbbs-universities", label: "Kathmandu" }],
};

const CITY_SLOT_LABEL: Record<string, string> = {
  "City/01_Skyline": "Skyline",
  "City/02_Landmark": "Landmark",
  "City/03_City_Centre": "City centre",
  "City/04_City_Life": "Everyday life",
};

/** Returns `uni:` image ids plus captions for a country's cities.
 *  One country with three universities (Russia) shows one slot from
 *  each city first, so the gallery reads as a tour of the country
 *  rather than four angles on one town. */
export function countryCityTiles(countrySlug: string): GalleryTile[] {
  const sources = COUNTRY_CITY_SOURCES[countrySlug];
  if (!sources) return [];

  const slots = Object.keys(CITY_SLOT_LABEL);
  const tiles: GalleryTile[] = [];

  if (sources.length === 1) {
    const { slug, label } = sources[0];
    slots.forEach((key) => {
      tiles.push({
        id: `uni:${slug}:${key}`,
        caption: `${label} — ${CITY_SLOT_LABEL[key]}`,
      });
    });
  } else {
    // Round-robin across cities, one slot each, then wrap.
    for (let i = 0; i < slots.length; i++) {
      const src = sources[i % sources.length];
      tiles.push({
        id: `uni:${src.slug}:${slots[i]}`,
        caption: `${src.label} — ${CITY_SLOT_LABEL[slots[i]]}`,
      });
    }
  }

  // Bento emphasis on the first and last tiles.
  if (tiles[0]) tiles[0].span = "col-span-2 row-span-2";
  if (tiles[3]) tiles[3].span = "col-span-2";
  return tiles;
}

/** Photographs used in the generic "life abroad" gallery. */
export const LIFE_GALLERY = [
  { id: "clinical-training", caption: "Clinical training from year three", span: "col-span-2 row-span-2" },
  { id: "laboratory", caption: "Modern teaching laboratories" },
  { id: "library", caption: "University libraries" },
  { id: "indian-food", caption: "Indian mess on or near every campus" },
  { id: "hostel-room", caption: "Hostel accommodation" },
  { id: "students-friends", caption: "An Indian community already there", span: "col-span-2" },
  { id: "lecture-hall", caption: "Lectures entirely in English" },
  { id: "anatomy", caption: "Anatomy and dissection halls" },
  { id: "graduation", caption: "Graduation — five to six years on", span: "col-span-2" },
  { id: "surgery", caption: "Operating theatre exposure" },
  { id: "students-study", caption: "FMGE preparation alongside coursework" },
] as const;

/** Service slug → image slot. */
export const SERVICE_IMAGE: Record<string, string> = {
  "career-counselling": "counselling",
  "university-selection": "student-laptop",
  "application-guidance": "documents",
  "admission-support": "consultation",
  "documentation-support": "visa-stamp",
  "visa-assistance": "visa-stamp",
  "travel-assistance": "aeroplane",
  "pre-departure-briefing": "airport",
  "post-arrival-support": "hostel-room",
  "fmge-next-guidance": "students-study",
};

/** Process step → image slot. */
export const PROCESS_IMAGE: Record<number, string> = {
  1: "counselling",
  2: "student-laptop",
  3: "documents",
  4: "visa-stamp",
  5: "airport",
};

/** The rolling strips on the homepage. */
export const MARQUEE_TOP = [
  "country-georgia",
  "clinical-training",
  "country-uzbekistan",
  "students-campus",
  "country-nepal-alt",
  "laboratory",
  "country-kyrgyzstan",
  "graduation",
];

export const MARQUEE_BOTTOM = [
  "library",
  "country-russia",
  "students-friends",
  "country-kazakhstan",
  "lecture-hall",
  "country-china",
  "indian-food",
  "country-georgia-alt",
];

export const MARQUEE_CAPTIONS: Record<string, string> = {
  "country-georgia": "Tbilisi, Georgia",
  "country-georgia-alt": "Caucasus, Georgia",
  "country-uzbekistan": "Uzbekistan",
  "country-nepal-alt": "Himalayas, Nepal",
  "country-kyrgyzstan": "Kyrgyzstan",
  "country-russia": "Russia",
  "country-kazakhstan": "Kazakhstan",
  "country-china": "China",
  "clinical-training": "Clinical training",
  "students-campus": "Campus life",
  "laboratory": "Teaching laboratories",
  "graduation": "Graduation day",
  "library": "University library",
  "students-friends": "Indian student community",
  "lecture-hall": "Lectures in English",
  "indian-food": "Indian mess",
};
