/* AUTO-GENERATED by scripts/fetch-university-logos.mjs
 * Re-run with:  npm run images:logos -- --force
 *
 * Each logo is the institution's own mark, taken from its own
 * website; `source` is the exact URL it came from so any one of
 * them can be re-checked without re-running the whole set.
 *
 * A university missing from this map is NOT an error — the UI falls
 * back to a monogram tile. University of South Asia is absent
 * because usa-kg.com is off the air (no A record).
 *
 * Logos are drawn on a light tile in both themes. Most of these are
 * dark-on-transparent and would vanish against the dark surface.
 */

export interface UniLogo {
  src: string;
  source: string;
  /** Which tile the mark needs behind it to stay visible. */
  tone: "light" | "dark";
}

export const UNIVERSITY_LOGOS: Record<string, UniLogo> = {
  "geomedi-university-georgia": {
    src: "/images/university-logos/geomedi-university-georgia.png",
    source: "https://geomedi.edu.ge/wp-content/uploads/2016/03/logo-geomedi.png",
    tone: "light",
  },
  "avicenna-batumi-medical-university": {
    src: "/images/university-logos/avicenna-batumi-medical-university.png",
    source: "https://www.avicenna.edu.ge/images/logo-ge.png",
    tone: "light",
  },
  "georgian-american-university": {
    src: "/images/university-logos/georgian-american-university.png",
    source: "https://gau.edu.ge/storage/app/media/logo/gau-ka-2.png",
    tone: "light",
  },
  "georgian-national-university-seu": {
    src: "/images/university-logos/georgian-national-university-seu.png",
    source: "https://seu.edu.ge/assets/DPqFdKZN.svg",
    tone: "dark",
  },
  "david-tvildiani-medical-university": {
    src: "/images/university-logos/david-tvildiani-medical-university.png",
    source: "https://dtmu.ge/wp-content/uploads/2023/12/dtmu-logo-EN.png",
    tone: "light",
  },
  "kazan-federal-university": {
    src: "/images/university-logos/kazan-federal-university.png",
    source: "https://stud-new2.kpfu.ru/img/logo_white_full.svg",
    tone: "dark",
  },
  "bashkir-state-medical-university": {
    src: "/images/university-logos/bashkir-state-medical-university.png",
    source: "https://bashgmu.ru/include/logo01.png",
    tone: "light",
  },
  "ulyanovsk-state-university": {
    src: "/images/university-logos/ulyanovsk-state-university.png",
    source: "https://ulsu.ru/static/img/logo150.svg",
    tone: "light",
  },
  "kemerovo-state-medical-university": {
    src: "/images/university-logos/kemerovo-state-medical-university.png",
    source: "https://kemgmu.ru/local/templates/pr.v1/images/logo_70.svg",
    tone: "light",
  },
  "kabardino-balkarian-state-university": {
    src: "/images/university-logos/kabardino-balkarian-state-university.png",
    source: "https://kbsu.ru/wp-content/themes/kbsu/img/logo-kbsu.png",
    tone: "dark",
  },
  "ingush-state-university": {
    src: "/images/university-logos/ingush-state-university.png",
    source: "https://inggu.ru/upload/images/logos/%D0%BB%D0%BE%D0%B3%D0%BE_%D0%BA%D0%BE%D0%BD%D1%81%D0%BE%D1%80%D1%86%D0%B8%D1%83%D0%BC_%D0%B2%D1%83%D0%B7%D0%BE%D0%B2__%D0%BA%D0%B0%D0%B2%D0%BA%D0%B0%D0%B7%D0%B0.svg",
    tone: "light",
  },
  "kazakh-national-medical-university": {
    src: "/images/university-logos/kazakh-national-medical-university.png",
    source: "https://kaznmu.edu.kz/wp-content/uploads/2024/03/logo-4.png",
    tone: "light",
  },
  "kazakh-russian-medical-university": {
    src: "/images/university-logos/kazakh-russian-medical-university.png",
    source: "https://new.krmu.edu.kz/assets/images/logo.png",
    tone: "light",
  },
  "nanjing-medical-university": {
    src: "/images/university-logos/nanjing-medical-university.png",
    source: "https://www.njmu.edu.cn/_upload/site/00/09/9/logo.png",
    tone: "light",
  },
  "southern-medical-university": {
    src: "/images/university-logos/southern-medical-university.png",
    source: "https://www.smu.edu.cn/images/24/12/19/1nbycjcao9/logo_pc.png",
    tone: "light",
  },
  "chongqing-medical-university": {
    src: "/images/university-logos/chongqing-medical-university.png",
    source: "https://www.cqmu.edu.cn/img/logo.png",
    tone: "dark",
  },
  "tianjin-medical-university": {
    src: "/images/university-logos/tianjin-medical-university.png",
    source: "https://www.tmu.edu.cn/_upload/site/00/04/4/logo.png",
    tone: "light",
  },
  "capital-medical-university": {
    src: "/images/university-logos/capital-medical-university.png",
    source: "https://www.ccmu.edu.cn/images/logo.png",
    tone: "dark",
  },
  "fergana-medical-institute-of-public-health": {
    src: "/images/university-logos/fergana-medical-institute-of-public-health.png",
    source: "https://fergmi.uz/wp-content/uploads/2025/04/fregana_logo-removebg-preview.png",
    tone: "light",
  },
};

/** Initials for the fallback tile — "Kazan Federal" → "KF".
 *
 *  Joining words are skipped: "University of South Asia" taken
 *  naively gives "UO", which looks like a typo rather than a mark. */
const SKIP = new Set(["of", "the", "and", "for"]);

export function monogram(shortName: string): string {
  const words = shortName
    .replace(/[^\p{L}\s-]/gu, "")
    .split(/[\s-]+/)
    .filter((w) => w && !SKIP.has(w.toLowerCase()));
  if (!words.length) return "??";
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return words
    .slice(0, 2)
    .map((w) => w[0])
    .join("")
    .toUpperCase();
}
