import {
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Banknote,
  BookOpen,
  Building,
  Building2,
  Calendar,
  Check,
  CircleDot,
  ClipboardCheck,
  Clock,
  Compass,
  Eye,
  FileCheck,
  FileCheck2,
  FileText,
  FolderCheck,
  Globe2,
  GraduationCap,
  Headphones,
  HeartHandshake,
  Landmark,
  Languages,
  LifeBuoy,
  Lightbulb,
  ListFilter,
  MapPin,
  MessageCircle,
  Plane,
  PlaneLanding,
  Presentation,
  Quote,
  Rocket,
  Route,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Stamp,
  Star,
  Stethoscope,
  Sun,
  Target,
  Terminal,
  Thermometer,
  TrendingDown,
  TrendingUp,
  UserCog,
  Users,
  UtensilsCrossed,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** String → component registry, so data files can name an icon
 *  without importing React. */
const REGISTRY: Record<string, LucideIcon> = {
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Banknote,
  BookOpen,
  Building,
  Building2,
  Calendar,
  Check,
  CircleDot,
  ClipboardCheck,
  Clock,
  Compass,
  Eye,
  FileCheck,
  FileCheck2,
  FileText,
  FolderCheck,
  Globe2,
  GraduationCap,
  Headphones,
  HeartHandshake,
  Landmark,
  Languages,
  LifeBuoy,
  Lightbulb,
  ListFilter,
  MapPin,
  MessageCircle,
  Plane,
  PlaneLanding,
  Presentation,
  Quote,
  Rocket,
  Route,
  ShieldCheck,
  Snowflake,
  Sparkles,
  Stamp,
  // The portfolio badge strip calls this "StampIcon"
  StampIcon: Stamp,
  Star,
  Stethoscope,
  Sun,
  Target,
  Terminal,
  Thermometer,
  TrendingDown,
  TrendingUp,
  UserCog,
  Users,
  UtensilsCrossed,
  Wallet,
  Zap,
};

export function Icon({
  name,
  className,
  strokeWidth = 1.8,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = REGISTRY[name] ?? Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden />;
}
